### ISSUE TITLE
Should we even have an image preview when the camera is in the air?

### ISSUE THREAD

**Issue by dbaldwin** [dbaldwin/DroidMapper#1]
Seems like we could conserve battery life without having to mess with photo previews. Perhaps we just have debug info that displays on the screen while photos are being taken.

**Comment by mtrl** [comment]
I agree, I don't think there's any need for a full-screen preview as it will just be of the ground most of the time.

Debug information with things such as shutter speed, number of images taken, a countdown to the next image and maybe a thumbnail of the last image would be nice.

**Comment by dbaldwin** [comment]
I've removed the screen preview and put some debug info on it. More debug info can always be added later.

https://github.com/dbaldwin/DroidMapper/commit/7fa3a7a591067eef53d9cb4643d1406edfb47d8c
